FORMAT: 1A

# My API

An API description.

## Group My Group

This is a group of resources

### Frob (/frobs/{id})

A frob does something.

#### GET

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "tag": "foo"
            }
