#!/bin/sh
if [ -d "src/" ]; then

	# Clear destination folder
	rm -rf lib/

	# Compile all .coffee files and move them into lib
	node_modules/.bin/coffee -b -c -o lib/ src/

	# Copy all .js files as they are
	cd src/
	find . -name "*.js" -type f -print | cpio -pvdmB ../lib/ 2> /dev/null
	cd ..
fi
