name: Docs
on:
  push:
    branches: [master]
    paths: ["docs/**"]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: deps-${{ hashFiles('**/package.json') }}
          restore-keys: |
            deps-
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Install Python dependencies
        run: pipenv install --dev
        working-directory: docs
      - name: Build docs
        run: |
          export PATH="$(yarn bin):$PATH"
          pipenv run make html
        working-directory: docs
